### ISSUE TITLE
Review: TeamCard.jsx and AllTeamInvitationCard.jsx

### ISSUE THREAD

**Issue by wenhaoq20** [bang-software/HACC-Hui-414f23#175]
## Overview

The focus for this code review will be centered around the TeamCard.jsx and AllTeamInvitationCard.jsx
Please pay attention too:
* Javascript issues
* React components

## Review Branch

review-006

## Files to review

* [TeamCard.jsx](../blob/main/app/imports/ui/components/participant/TeamCard.jsx)
* [AllTeamInvitationCard.jsx](../blob/main/app/imports/ui/components/administrator/AllTeamInvitationCard.jsx)

## Checklists

* [Architecture](../blob/main/checklists/architecture-checklist.md)
* [Design](../blob/main/checklists/design-checklist.md)
* [JS](../blob/main/checklists/js-checklist.md)
* [React](../blob/main/checklists/react-checklist.md)
* [Testing](../blob/main/checklists/testing-checklist.md)

## Due date

Monday, October 16, 9:00 AM

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414f23/morea/review/reading-idpm-review.html

**Comment by Louie808** [comment]
### AllTeamInvitationCard.jsx
RE-09: Prefer functions vs. classes for stateless components
JS-05: Avoid lodash functions. Use ES6 built-in functions
RE-06: Define constants with useTracker()
RE-07: Doing data retrieval inside render()
DE-00: Inline styling
RE-00: Convert to bootstrap
<hr>

### TeamCard.jsx
RE-09: Prefer functions vs. classes for stateless components
RE-06: Define constants with useTracker() - inside buildTheTeam()
RE-07: Doing data retrieval inside render() - inside handleLeaveTeam()
JS-05: Avoid lodash functions. Use ES6 built-in functions
RE-00: Convert to bootstrap

**Comment by yongsungm** [comment]
## TeamCard.jsx

RE-09: L17 Prefer functions vs. classes for stateless components
RE-10: Avoid widget and card in names
JS-06: L32 avoid console.logs
JS-05: L4, 22, 27 Avoid underscore functions. Use ES6 built-in functions
L18 change name from 'buildTheTeam' to 'buildTeam'


## AllTeamInvitationCard.jsx

RE-09: L16 Prefer functions vs. classes for stateless components
JS-04: L21, 26 Use arrow functions when appropriate
JS-05: L11, 36 Avoid underscore functions. Use ES6 built-in functions
DE-05: L18 Unnecessary comment

**Comment by EvanAraki** [comment]
### TeamCard.jsx
JS-05 Line 22, 27 use ES6 functions
DE-06 confusing variable names, ie: tCs, teamPs

### AllTeamInvitationCard
JS-05 Line 36 use ES6 functions
-confusing inconsistencies: ie color being defined by hex and rgb value in same file

Both missing any documentation

**Comment by wenhaoq20** [comment]
# TeamCard.jsx
JS-04: use arrow function for line 18, 31
JS-05:  functions at line 22, 27m
JS-06: console.log at line 32
JS-07: missing JSDoc
RE-04: Destructure props line 58
RE-09: prefer function component

# AllTeamInvitationCard.jsx
JS-04: use arrow function for line 21, 26
JS-05:  functions at line 36
JS-07: missing JSDoc
RE-04: Destructure props
RE-09: prefer function component

**Comment by sukaryo-heilscher** [comment]
TeamC:
JS-05: Uses Iodash.
JS-06: L32, 42, 46, 51 console.log
RE-04: Destructure props.
RE-06: Change buildTheTeam to useTracker probably.
RE-09: Convert class to function.

AllTeamInvC:
DE-06: L2-9 weird spacing.
DE-08: L22, 45, 57 Colors should be imports.
RE-04: Destructure props.
RE-06: Add useTracker probably?
RE-09: Convert class to function.

**Comment by gitCarrot** [comment]
- TeamCard.jsx
JS-05: On L4, L22, and L27, lodash functions are being used.
RE-06: useTracker() hook should be used to retrieve reactive Meteor data instead of making these calls within methods like buildTheTeam.
RE-07: Methods such as handleLeaveTeam seem to perform data retrieval or manipulations which should be separated from the rendering concerns.
JS-06: There are console.log statements on L37 and L45
RE-00: If the project is transitioning to Bootstrap, the component's UI elements and styling should be updated accordingly.
RE-09: Prefer using functional components with hooks instead of class components for simplicity and better readability.

- AllTeamInvitationCard.jsx
DE-00: Inline styling is found in various places in the component. 
RE-09: Similar to TeamCard, it's recommended to use functional components.
JS-05: Lodash functions are used on L11 and L36. replacing with native ES6 functi
JS-04: Functions changeBackground and onLeave on L21 and L26 can be converted to arrow functions, making the code more concise.
RE-00: As with TeamCard, if the transition is towards Bootstrap, the UI elements and styles should be refactored to adhere to Bootstrap.

**Comment by wenhaoq20** [comment]
# Outcome of the meeting
- Use useTracker for all collection data retrieval.
