### ISSUE TITLE
Review: AdminEditTeamWidget.js and InterestedParticipants.jsx

### ISSUE THREAD

**Issue by wenhaoq20** [bang-software/HACC-Hui-414f23#191]
## Overview

The focus for this code review will be centered around AdminEditTeamWidget.js and  InterestedParticipants.jsx.
Please pay attention too:
* Javascript issues
* React components

## Review Branch

review-008

## Files to review

* [AdminEditTeamWidget.js](../blob/main/app/imports/ui/components/administrator/AdminEditTeamWidget.js)
* [InterestedParticipants.jsx](../blob/main/app/imports/ui/components/participant/InterestedParticipants.jsx)

## Checklists

* [Architecture](../blob/main/checklists/architecture-checklist.md)
* [Design](../blob/main/checklists/design-checklist.md)
* [JS](../blob/main/checklists/js-checklist.md)
* [React](../blob/main/checklists/react-checklist.md)
* [Testing](../blob/main/checklists/testing-checklist.md)

## Due date

Monday, October 30, 9:00 AM

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414f23/morea/review/reading-idpm-review.html

**Comment by MacabanteJ** [comment]
AdminEditTeamWidget.js
JS-03: 71 - desctructure this.props.members
JS-05: 71 - utilize built-in functions over underscore functions
JS-06: 56, 57 - remove console.logs
JS-07: JSDoc comment needs updating (deprecated?)
RE-07: 72 - retrieves data inside render()
RE-09: Functions over classes

InterestedParticipants.jsx
JS-03: 31, 45, 61, 76, 92 - destructure prop
JS-05: 49, 80, 96 - replace underscore functions
JS-06: 88, 143, 150, 152 - remove console.logs
ES-01: 1, 117, 145, 151, 154, 159 - remove max-len disable
RE-09: Functions over classes

**Comment by EvanAraki** [comment]
### AdminEditTeamWidget.js

JS-05: L71, 132 replace with es6 functions
JS-06: L56, 57 remove console.log
- basic stuff like with to use tracker and semantic to bootstrap

### InterestedParticipants.jsx

JS-05: L49, 80, 96 - replace with ES6 functions
JS-06/ DE-04: L57, 72, 88, 143-145, 148, 150-152, 154, 159, 165,  remove console log and unnecessary commented out code

-L118-121, refactor this, possibly by assigning values to variables for readability and so we can remove the disable eslint comment on L117
- basic stuff like with to use tracker and semantic to bootstrap

**Comment by wenhaoq20** [comment]
# AdminEditTeamWidget.js
- AR-01: why is the file extension js?
- JS-04: use arrow function (line 43)
- JS-05: use js built in function (line 71, 132)
- JS-06: avoid console log (line 56, 57)
- RE-04: destructure props
- RE-09: convert to functional component
- Convert withTracker to useTracker

# InterestedParicipants.jsx
- DE-01: refactor two render to a ternary statement
- JS-04: use arrow function (line 47, 63, 78, 94)
- JS-05: use js built in function (line 49, 80, 96)
- JS-06: remove commented out console.log (line 57, 72,88)
- JS-07: JSDoc are missing for some functions
- ES-01: reformat for max length line (line 117)
- RE-04: destructure props
- RE-09: convert to functional component
- Convert withTracker to useTracker

**Comment by yongsungm** [comment]
## AdminEditTeamWidget.js

RE-09: L33 Prefer functions vs. classes for stateless components
DE-05: L22-25 innaccurate comment 
JS-05: L10, 71, 132 Avoid underscore functions. Use ES6 built-in functions

Line 128 use useTracker instead of withTracker
Line 140 withRouter is deprecated
Line 105 prefer reusable styles

## InterestedParticipants.jsx

RE-09: L27 Prefer functions vs. classes for stateless components
JS-05: L10, 49, 80, 96,  Avoid underscore functions. Use ES6 built-in functions
DE-05: L57, 72, 143, 144, 148, 150-152, 154, 159 165 uneccessary comments
RE-04: L31, 45, 61, 76, 92, 111, 118 Destructure props in component parameter.

Line 142 use useTracker instead of withTracker

**Comment by sukaryo-heilscher** [comment]
AdminEditTeamW:
DE-08: L80, 91, 107 Colors should be imports.
JS-05: Uses Iodash.
ES-01: align doesn't exist.
RE-03: Default export is renamed.
RE-04: Destructure props.
RE-06: Put collection calls in useTracker.
RE-09: Convert class to function.

InterestedP:
DE-05: Clean up comments.
DE-06: L119-121 Weird spacing. Also, can combine the return at L32 with the other as a ternary.
JS-05: Uses Iodash.
ES-01: align doesn't exist. Also warning suppressions.
RE-04: Destructure props.
RE-06: Put collection calls in useTracker.
RE-09: Convert class to function.

**Comment by Louie808** [comment]
### AdminEditTeamWidget.jsx
RE-09: Prefer functions vs. classes for stateless components
JS-05: Avoid lodash functions. Use ES6 built-in functions
RE-06: Define constants with useTracker()
RE-07: Doing data retrieval inside render()
DE-00: Inline styling
RE-00: Convert to bootstrap
<hr>

### InterestedParticipants.jsx
DE-01: Possible refactor to reduce duplication?
RE-09: Prefer functions vs. classes for stateless components
RE-07: Doing data retrieval inside render() 
DE-04: Eliminate large comment blocks.
JS-05: Avoid lodash functions. Use ES6 built-in functions
RE-06: Define constants with useTracker()
DE-00: Inline styling
RE-00: Convert to bootstrap

**Comment by gitCarrot** [comment]
- AdminEditTeamWidget.jsx

JS-04: Convert methods like submit to arrow functions.
JS-05: Lodash functions detected in render method
JS-07: Missing JSDoc for the class AdminEditTeamWidget
RE-04: Destructure props and state in the render method for clarity.
RE-06: Consider changing to useTracker from withTracker.
RE-09: Since the component mainly consists of a render method, it's a good candidate for conversion into a function component.

- InterestedParticipants.jsx
JS-04: Convert methods like render to arrow functions.
JS-05: Lodash functions detected in multiple helper functions (e.g., getDeveloperSkills, getInterestedDevelopers, etc.).
JS-07: Missing JSDoc for the class InterestedParticipants
RE-04: Destructure props in the render method for clarity.
RE-06: Consider changing to useTracker from withTracker.
RE-09: Conversion into a function component.

**Comment by wenhaoq20** [comment]
- Need to modified some code in the collection
