### ISSUE TITLE
Review: AdminEditTeamPage.jsx and ParticipationForm.jsx

### ISSUE THREAD

**Issue by wenhaoq20** [bang-software/HACC-Hui-414f23#231]
## Overview

The focus for this code review will be centered around the AdminEditTeamPage.jsx and ParticipationForm.jsx.
Please pay attention too:
* Javascript issues
* React components

## Review Branch

review-011

## Files to review

* [AdminEditTeamPage.jsx](../blob/main/app/imports/ui/pages/administrator/AdminEditTeamPage.jsx)
* [ParticipationForm.jsx](../blob/main/app/imports/ui/pages/participant/ParticipationForm.jsx)

## Checklists

* [Architecture](../blob/main/checklists/architecture-checklist.md)
* [Design](../blob/main/checklists/design-checklist.md)
* [JS](../blob/main/checklists/js-checklist.md)
* [React](../blob/main/checklists/react-checklist.md)
* [Testing](../blob/main/checklists/testing-checklist.md)

## Due date

Monday, November 20, 9:00 AM

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414f23/morea/review/reading-idpm-review.html

**Comment by Louie808** [comment]
### AdminEditTeamPage.js
DE-01: Refactor to reduce duplication
#### Code is exact copy of the participant so it can be refactored
Only problem is that participant version is a modal and not a page like this one. SO having redirect to reroute was a problem I faced when just calling the participant component into this file. 
DE-00: Inline styling
<hr>

### ParticipationForm.jsx
RE-09: Prefer ARROW functions over regular function for ES6
JS-06: console.log L39
DE-00: Inline styling 
Whats with L59-L66. It can use autoform now.

**Comment by EvanAraki** [comment]
### AdminEditTeamPage.js

DE-01: Could Refactor to reduce duplication in useTracker, however like every useTracker looks like this so im not sure how necessary that is 

### ParticipationForm.jsx

JS-06:  L39 remove console log

convert to arrow function

**Comment by MacabanteJ** [comment]
AdminEditTeamPage.jsx
Can remove DevPost portion (per Moore's instruction) - L75, 100, 145
Standardize inline styling - L142, 144, 159

ParticipationForm.jsx
Standardize inline styling - L57, 58, 91
JS-06: L39 - remove console.log

**Comment by sukaryo-heilscher** [comment]
AdminEditTeamP:
DE-08: L139, 144 Colors should be imports.
TA-01/02: No tests? Unless I'm blind.

Might be nice to have a cancel button.

ParticiForm:
DE-05: L15 Comment incorrectly calls this the landing page.

Not necessarily wrong, but "export default function" is different from what we normally do.
Since we're only updating the Participant collection and not pulling from it, there's no need for useTracker?

**Comment by yongsungm** [comment]
## AdminEditTeamPage.jsx

L137-144 import styles instead of using in-line styling

## ParticipationForm.jsx

JS-04: L18 Use arrow functions when appropriate
JS-06: L39 Avoid console.logs

**Comment by gitCarrot** [comment]
AdminEditTeamPage.jsx
DE-01: Refactor to Reduce Duplication: Similar mapping logic is repeated in useTracker. 
JS-02: Use Spread Operator: Implement spread operator in object updates within submit function.
JS-06: Remove Console Logs: Eliminate console.error from error handling.
JS-07: Add JSDoc Comments: Include JSDoc comments for better documentation and clarity.
ParticipationForm.jsx
JS-06: Remove Console Logs
DE-00: Inline Styling: Consider using external CSS for styling instead of inline styles.
RE-00: Convert to Bootstrap
