### ISSUE TITLE
Review: ManageHaccWidget.jsx and HelpPage.jsx

### ISSUE THREAD

**Issue by wenhaoq20** [bang-software/HACC-Hui-414f23#42]
## Overview

The focus for this code review will be centered around the ManageHaccWidget.jsx and HelpPage.jsx.    
Please pay attention too:
* Javascript issues
* React components

## Review Branch

review-002

## Files to review

* [ManageHaccWidget.jsx](../blob/main/app/imports/ui/components/administrator/ManageHaccWidget.jsx)
* [HelpPage.jsx](../blob/main/app/imports/ui/pages/HelpPage.jsx)

## Checklists

* [Architecture](../blob/main/checklists/architecture-checklist.md)
* [Design](../blob/main/checklists/design-checklist.md)
* [JS](../blob/main/checklists/js-checklist.md)
* [React](../blob/main/checklists/react-checklist.md)
* [Testing](../blob/main/checklists/testing-checklist.md)

## Due date

Monday, September 18, 9:00 AM

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414f23/morea/review/reading-idpm-review.html

**Comment by EvanAraki** [comment]
### ManageHaccWidget.jsx
DE-06: Reduce usage of inline style to standardize UI and make code more readable and standardize design
DE-05 L96 L117: either break code into 2 lines or change eslint max line length property, ideally first option to make code more readable
DE-06 little to no documentation on how functions like toggleTeam (L30-43) work

Informal comments: I'm not sure if its just me but this widget is incredibly dense, as mentioned the documentation is absent and trying to understand how this interacts with other components is a nightmare especially with calls like `const collectionName = CanCreateTeams.getCollectionName();` (why is the collection called CanChangeChallenges??)

=======================================================
### HelpPage.jsx
DE-06: Reduce usage of inline style to standardize UI and make code more readable and standardize design

Informal comments: general clunky formatting, eg: L26-28, <b> nested inside an <h1>

**Comment by Louie808** [comment]
### ManageHaccWidget.jsx
- use function instead of classes
-  Retrieves collection data inside render()
- Inline styling, move to CSS classes or stylesheets
- Use Destructuring in function parameters, destructure "props"

- Possibly use a function to map for repetitive components
ex. 
```
const renderItems = (items, WidgetComponent) => {
  return items.map((item) => <WidgetComponent key={item._id} item={item} />);
};

// In the render method:
{renderItems(this.props.challenges, ChallengesAdminWidget)}
{renderItems(this.props.skills, SkillsAdminWidget)}
{renderItems(this.props.tools, ToolsAdminWidget)}
```
<hr>

### HelpPage.
- use function instead of classes
- move all inline styles into a CSS class file just for helppage
- can easily divide the components into different subcomponent functions and then call those.

**Comment by Louie808** [comment]
### ManageHaccWidget.jsx
- use function instead of classes
-  Retrieves collection data inside render()
- Inline styling, move to CSS classes or stylesheets
- Use Destructuring in function parameters, destructure "props"
- Possibly use a function to map for repetitive components

ex. 
```
const renderItems = (items, WidgetComponent) => {
  return items.map((item) => <WidgetComponent key={item._id} item={item} />);
};

// In the render method:
{renderItems(this.props.challenges, ChallengesAdminWidget)}
{renderItems(this.props.skills, SkillsAdminWidget)}
{renderItems(this.props.tools, ToolsAdminWidget)}
```
<hr>

### HelpPage.
- use function instead of classes
- move all inline styles into a CSS class file just for helppage
- can easily divide the components into different subcomponent functions and then call those.

**Comment by wenhaoq20** [comment]
# ManageHaccWidget
RE-09: prefer function
DE-01: too many in line styles, put styles in a separate css file
JS-04: need change withTracker to useTracker or withTracker()
RE-06: withTracker does not define constants
RE-04: props are not destructured in component parameter
Re-10: widge in the name

# HelpPage
DE-01: too many in line styles, put styles in a separate css file
ES-01: <text> is invalid
JS-07: no JSDoc

**Comment by yongsungm** [comment]
## ManageHaccWidget.jsx

JS-04: L23 arrow function instead of class
DE-05: L61 commented console.log

## HelpPage.jsx

DE-01: L19, 23, 59, 63, 128, 132, styling is repeated
L58, 127 repeat styling

**Comment by sukaryo-heilscher** [comment]
save background colors to an import

Widget:
DE-01: Table.Row with Name, Description, Edit, & Delete is duplicated. Can be refactored.
ES-02: Get rid of ESLint disable. (Pretty sure we changed that rule already.)
RE-09: Can use const instead of states. Convert to function.
RE-10: ...I kinda like having Widget in the name though? Maybe can just shorten it to W.
TI-01: Needs a test.

Page:
DE-01: style={{ flex: 1, backgroundColor: 'lightgray', height: '1.5px', margin: '10px' }} is repeated at many points. Can this be made into a constant?
RE-01: Currently uses mostly plain old HTML & CSS. Can this be broken up into components?

**Comment by gitCarrot** [comment]
## ManageHaccWidget.jsx

RE-01: React state can be initialized using a constructor or a state class property. Choose one for consistency.
RE-02: The component is fetching data from the Meteor server in a non-reactive way. Consider using a reactive data fetching mechanism to get real-time updates.
RE-03: Direct navigation (Link) is used inside buttons, which can lead to accessibility issues. Consider using navigational methods or making the entire button a link.

## HelpPage.jsx

DE-01: Inline styles are used extensively. Consider using external CSS classes to keep the design consistent and codebase maintainable.

RE-01: The component is functional and stateless, which is suitable for its current use. Ensure any stateful logic in the future is incorporated properly.
RE-02: Use of text as a component in <Link to='create-team'><text>Create Teams Page</text></Link>. It's not a standard React or HTML element. Ensure it's either a custom component or replace it with a standard element like <span>.
